services:
  fleetdm:
    image: ${IMAGE_NAME:-fleetdm/fleet}:${TAG:-latest}
    container_name: fleetdm
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - "8080:8080"
    command: ["fleet", "serve"]
    volumes:
      - ${MNT_DIR}/data/fleetdm:/data
      - ${MNT_DIR}/config/fleetdm:/config
    networks:
      - vnet-frontend
      - vnet-backend

networks:
  vnet-frontend:
    external: true
  vnet-backend:
    external: true
